var books = [
   { title: "Catch-22", read: true, own: false, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Lolita", read: true, own: true, loaned: false, readabilityEase: "hardSlog", insightsOffered: "someValue", enjoymentLevel: "sufferedThrough" },
   { title: "The Catcher in the Rye", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Great Gatsby", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "someValue", enjoymentLevel: "thoroughlyRelished" },
   { title: "1984 (Nineteen Eighty-Four)", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "To Kill a Mockingbird", read: true, own: false, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Beloved", read: true, own: false, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Invisible Man", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Grapes of Wrath", read: false, own: true, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Sound and the Fury", read: true, own: true, loaned: false, readabilityEase: "hardSlog", insightsOffered: "someValue", enjoymentLevel: "likedModerately" },
   { title: "A Passage to India", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Midnight's Children", read: false, own: true, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Mrs. Dalloway", read: false, own: true, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "On the Road", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Rabbit Angstrom Tetrology", read: false, own: true, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Slaughterhouse-Five (Slaughterhouse-5)", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Adventures of Huckleberry Finn", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Things Fall Apart", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Ulysses", read: false, own: true, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Wuthering Heights", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Go Tell It on the Mountain", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "Moby Dick; or, The Whale", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Native Son", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Pride and Prejudice", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "someValue", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Sun Also Rises", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Their Eyes Were Watching God", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "All the King's Men", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Brave New World", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Charlotte's Web", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Frankenstein; or, The Modern Prometheus", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Gone with the Wind", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Jane Eyre", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "My Antonia", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Age of Innocence", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Big Sleep", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Call of the Wild", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Golden Notebook", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Heart is a Lonely Hunter", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Hitchhiker's Guide to the Galaxy", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "someValue", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Life and Opinions of Tristram Shandy, Gentleman", read: true, own: true, loaned: false, readabilityEase: "hardSlog", insightsOffered: "quiteInfluential", enjoymentLevel: "sufferedThrough" },
   { title: "The Lord of the Rings", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Maltese Falcon, The Thin Man, Red Harvest", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "To The Lighthouse", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Tropic of Cancer", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "A House for Mrs. Biswas", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Atlas Shrugged", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Brideshead Revisited", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "David Copperfield", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Death Comes for the Archbishop", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Heart of Darkness", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "sufferedThrough" },
   { title: "Howards End", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Infinite Jest", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Light in August", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Middlemarch/Silas Marner/Amos Barton", read: false, own: false, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Sons and Lovers", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Sophie's Choice", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Adventures of Augie March", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Color Purple", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Handmaid's Tale", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The History of Tom Jones, a Foundling", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "The House of Mirth", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "sufferedThrough" },
   { title: "The London Trilogy (Money [A Suicide Note], London Fields, The Information)", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Lord of the Flies", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Old Man and the Sea", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Once and Future King", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Prime of Miss Jean Brodie", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Scarlet Letter", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The World According to Garp", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Wide Sargasso Sea", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "A Bend in the River", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "A Clockwork Orange", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "A Confederacy of Dunces", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "A Dance to the Music of Time ('twelve movement' series)", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "A Portrait of the Artist as a Young Man", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Alice's Adventures in Wonderland", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "someValue", enjoymentLevel: "thoroughlyRelished" },
   { title: "American Pastoral", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Animal Farm", read: true, own: false, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "Appointment in Samara", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "As I Lay Dying", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Atonement", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Blood Meridian, or the Evening Redness in the West", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Fahrenheit 451", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Finnegans Wake", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "For Whom the Bell Tolls", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Great Expectations", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Gulliver's Travels", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "Hamlet", read: true, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Herzog", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Housekeeping", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "I, Claudius", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Lonesome Dove", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Lucky Jim", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Main Street", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Naked Lunch", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Neuromancer", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Nostromo", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Of Mice and Men", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "One Flew Over the Cuckoo's Nest", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Pale Fire", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Portnoy's Complaint", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Scoop", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "quiteInfluential", enjoymentLevel: "thoroughlyRelished" },
   { title: "Song of Solomon", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Tess of the D'Urbervilles", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "The Awakening", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Bridge of San Luis Rey", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Corrections", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Fountainhead", read: true, own: false, loaned: false, readabilityEase: "variablePacing", insightsOffered: "quiteInfluential", enjoymentLevel: "likedModerately" },
   { title: "The Golden Bowl", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Hobbit", read: true, own: true, loaned: false, readabilityEase: "variablePacing", insightsOffered: "someValue", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Lion, the Witch, and the Wardrobe", read: true, own: true, loaned: false, readabilityEase: "pageTurner", insightsOffered: "someValue", enjoymentLevel: "thoroughlyRelished" },
   { title: "The Moviegoer", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Naked and the Dead", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Portrait of a Lady", read: true, own: true, loaned: false, readabilityEase: "hardSlog", insightsOffered: "someValue", enjoymentLevel: "likedModerately" },
   { title: "The Sheltering Sky", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Sot-Weed Factor", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Stand", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "The Wind in the Willows", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "U.S.A (trilogy)", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Under the Net", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "Under the Volcano", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
   { title: "White Noise", read: false, own: false, loaned: false, readabilityEase: "", insightsOffered: "", enjoymentLevel: "" },
];